Adding `upload` method for single attachment ID upload
Automattic/s3-media-sync pull request #20
Opened 2023-10-04 06:00 UTC by ovidiul

This PR will address https://github.com/Automattic/s3-media-sync/issues/19 whereby we introduce a new command to upload a single post_type attachment based on its ID.

Example use case

```
wp s3-media upload 12345
```

The benefit of this command is that, based on a known lists of attachment IDs we need to upload, we could combine it with xargs like

```
xargs -n 1 -P 5 -a attachment_ids.txt wp s3-media upload
```

to granularly upload them to the S3 bucket, and so avoiding the necessity of a full sync using `upload-all`.

2023-10-06 18:19 UTC, WickedWolfy commented
Minus the difference in spacing/tabbing between different code lines, I would like to raise to question the use of `WP_CLI::error` ([doc](https://make.wordpress.org/cli/handbook/references/internal-api/wp-cli-error/)) and maybe lean more in favor of `WP_CLI::warning` ([doc](https://make.wordpress.org/cli/handbook/references/internal-api/wp-cli-warning/)).
The reason being is that `error` exits the process after output. This was a current frustration with executing the task last time - with a large amount of items to move over, re-running the script becomes a silly nuisance!
If it would be possible to collect "issue" information in a log file or output it after the full execution, I would consider that a more favorable outcome, since at least some backup work is done and the logged issues are in a full list, rather than going through the madness of having to rerun the script to test one file after 60% of inventory and 3 hours of runtime.

If there is an interest in a logging to file I can definitely push some code.

2023-10-09 05:06 UTC, ovidiul commented
> Minus the difference in spacing/tabbing between different code lines, I would like to raise to question the use of `WP_CLI::error` ([doc](https://make.wordpress.org/cli/handbook/references/internal-api/wp-cli-error/)) and maybe lean more in favor of `WP_CLI::warning` ([doc](https://make.wordpress.org/cli/handbook/references/internal-api/wp-cli-warning/)). The reason being is that `error` exits the process after output. This was a current frustration with executing the task last time - with a large amount of items to move over, re-running the script becomes a silly nuisance! If it would be possible to collect "issue" information in a log file or output it after the full execution, I would consider that a more favorable outcome, since at least some backup work is done and the logged issues are in a full list, rather than going through the madness of having to rerun the script to test one file after 60% of inventory and 3 hours of runtime.
> 
> If there is an interest in a logging to file I can definitely push some code.

Considering the new method will upload a single file only, its probably fine to let it stop on Error and not consume more resources than needed, the Warning might be more useful when the upload-all method is used, but for legacy reasons, this PR is not about that method.

Thanks for pointing out the spaces @WickedWolfy , thats now addressed.

2023-10-12 18:35 UTC, WickedWolfy approved these changes
Discussed online and offline and main points are reasonable.

Code looks good.

2025-01-01 15:33 UTC, GaryJones requested changes

2025-01-01 15:33 UTC, GaryJones commented on inc/class-s3-media-sync-wp-cli.php
> +                $to      = S3_Media_Sync::init()->get_s3_bucket_url();
These two lines are space-indented.

2025-01-01 15:33 UTC, GaryJones commented on inc/class-s3-media-sync-wp-cli.php
> +		$attachment_id = intval( $args[0] );
```suggestion
		$attachment_id = absint( $args[0] );
```

2025-01-01 15:33 UTC, GaryJones commented on inc/class-s3-media-sync-wp-cli.php
> +		if ( $attachment_id <= 0 ) {
```suggestion
		if ( $attachment_id === 0 ) {
```

2025-01-01 15:33 UTC, GaryJones commented on inc/class-s3-media-sync-wp-cli.php
> +		if ( empty( $url ) ) {
Let's avoid `empty()`, and be specific about what we're testing for what might come back from `wp_get_attachment_url()`.

```suggestion
		if ( false === $url || '' === $url ) {
```

2025-01-01 15:33 UTC, GaryJones commented on inc/class-s3-media-sync-wp-cli.php
> +		if (curl_errno($ch)) {
```suggestion
		if ( curl_errno( $ch ) ) {
```

2025-01-01 15:33 UTC, GaryJones commented on inc/class-s3-media-sync-wp-cli.php
> +			WP_CLI::error( 'cURL error for Attachment ID ' . $attachment_id . ': ' . curl_error( $ch ) );
```suggestion
			WP_CLI::error( 'cURL error for attachment ID ' . $attachment_id . ': ' . curl_error( $ch ) );
```

2025-01-01 15:33 UTC, GaryJones commented on inc/class-s3-media-sync-wp-cli.php
> +		if (curl_errno($ch)) {
```suggestion
		if ( curl_errno( $ch ) ) {
```

2025-01-01 15:33 UTC, GaryJones commented on inc/class-s3-media-sync-wp-cli.php
> +			WP_CLI::error( 'cURL error for Attachment ID ' . $attachment_id . ': ' . curl_error( $ch ) );
```suggestion
			WP_CLI::error( 'cURL error for attachment ID ' . $attachment_id . ': ' . curl_error( $ch ) );
```

2025-01-01 15:33 UTC, GaryJones commented on inc/class-s3-media-sync-wp-cli.php
> +			WP_CLI::error( 'Failed to fetch attachment from URL for Attachment ID ' . $attachment_id . ': ' . $url );
```suggestion
			WP_CLI::error( 'Failed to fetch attachment from URL for attachment ID ' . $attachment_id . ': ' . $url );
```

2025-01-02 07:18 UTC, ovidiul commented on inc/class-s3-media-sync-wp-cli.php
> +                $to      = S3_Media_Sync::init()->get_s3_bucket_url();
Fixed now

2025-01-02 11:58 UTC, GaryJones approved these changes

2025-01-02 11:59 UTC, merged